language: java

env:
  - CODECOV_TOKEN="912f21a4-e41f-43f9-b7d2-e65918f173f0"

test:
  post:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
